wallpaper {
    monitor = DP-2
    path = /home/adrian/Downloads/wallpaper5.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/adrian/Downloads/wallpaper5.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = /home/adrian/Downloads/a_moon_over_mountains_and_clouds.png
    fit_mode = cover
}
