wallpaper {
    monitor = DP-1
    path = /home/adrian/Downloads/moonlight-window-3840x2160-22169.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/adrian/Downloads/moonlight-window-3840x2160-22169.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/adrian/Downloads/moonlight-window-3840x2160-22169.png
    fit_mode = cover
}
